services:
  sublime-text-kasm:
    image: "kasmweb/sublime-text:1.19.0-rolling-weekly@sha256:184edb41c147b4e0634e6522a65569dc0074f703c3fbb528ac687816662a8f39"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTPS}:6901"
    environment:
      - VNC_PW=${HTTP_PWD}
    shm_size: ${SHM_SIZE}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl --insecure --fail --silent --show-error
          --user "kasm_user:$$VNC_PW"
          https://127.0.0.1:6901/
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 5
    volumes:
      - "${APP_DATA_DIR}:/home/kasm-user"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
