services:
  romm:
    image: "rommapp/romm:5.3.1"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - ROMM_DB_DRIVER=${PANEL_DB_TYPE}
      - DB_HOST=${PANEL_DB_HOST}
      - DB_PORT=${PANEL_DB_PORT}
      - DB_NAME=${PANEL_DB_NAME}
      - DB_USER=${PANEL_DB_USER}
      - DB_PASSWD=${PANEL_DB_USER_PASSWORD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - SCREENSCRAPER_USER=${SCREENSCRAPER_USER}
      - SCREENSCRAPER_PASSWORD=${SCREENSCRAPER_PASSWORD}
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY}
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY}
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED}
    volumes:
      - "${APP_DATA_DIR}/romm:/romm"
      - "${APP_DATA_DIR}/redis:/redis-data"
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS http://127.0.0.1:8080/api/heartbeat >/dev/null
      start_period: 120s
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
