services:
  this-week-in-past:
    image: "rouhim/this-week-in-past:3.0.3@sha256:9dc78637bf7f07e941a19b7948a4ff111e521a772188ca85cb56ef44fa2d0402"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - RESOURCE_PATHS=/resources
      - DATA_FOLDER=/data
      - PORT=8080
      - SLIDESHOW_INTERVAL=${SLIDESHOW_INTERVAL}
      - RANDOM_SLIDESHOW=${RANDOM_SLIDESHOW}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${PHOTO_LIBRARY_PATH}:/resources:ro"
      - "${APP_DATA_DIR}:/data"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
