services:
  this-week-in-past:
    image: "rouhim/this-week-in-past:3.0.2@sha256:a04b2d59d433de0399c86161744cdba24ec8bc74193c7c3530a62d8469958056"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - RESOURCE_PATHS=/resources
      - DATA_FOLDER=/data
      - PORT=8080
      - SLIDESHOW_INTERVAL=${SLIDESHOW_INTERVAL}
      - RANDOM_SLIDESHOW=${RANDOM_SLIDESHOW}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${PHOTO_LIBRARY_PATH}:/resources:ro"
      - "${APP_DATA_DIR}:/data"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
