services:
  silverbullet:
    image: "ghcr.io/silverbulletmd/silverbullet:latest@sha256:e36808c27717e6c1d97e2421d6da263a16f273db91768bec2c227f28a9759086"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      SB_USER: "${SB_USERNAME}:${SB_PASSWORD}"
    volumes:
      - "${SPACE_DIR}:/space"
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://127.0.0.1:3000/.instance || exit 1
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
