networks:
  1panel-network:
    external: true
services:
  kimai:
    image: "linuxserver/kimai:2.68.0"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://kimai:${DB_PASSWORD}@kimai-db:3306/kimai?charset=utf8mb4&serverVersion=11.4.2-MariaDB
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    depends_on:
      - kimai-db
    labels:
      createdBy: "Apps"
  kimai-db:
    image: "mariadb:11.4"
    restart: always
    networks:
      - 1panel-network
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=kimai
      - MARIADB_USER=kimai
      - MARIADB_PASSWORD=${DB_PASSWORD}
    labels:
      createdBy: "Apps"
