services:
  dbx:
    image: "t8y2/dbx@sha256:98f29560779809a1288bd61826f16d0edd8b7b2b9d493a010be7a93ccdfdbb5c"
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:4224"
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
