services:
  dbx:
    image: "t8y2/dbx@sha256:115593a8b1df524a148a3e45d02f2c3e04c0b43a0bfee0a7dab589f6aa9d1f21"
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:4224"
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
