services:
  dbx:
    image: "t8y2/dbx@sha256:033692fd56cad4c4033c8659e7225a7f319c7a169b2b75676cfc77bd7d545d8d"
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:4224"
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
