networks:
  1panel-network:
    external: true
services:
  lychee:
    image: "linuxserver/lychee:7.10.0"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${PICTURES_PATH}:/pictures"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_USERNAME=${DB_USERNAME:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_DATABASE=${DB_DATABASE}
      - APP_NAME=${APP_NAME:-Lychee}
      - APP_URL=${APP_URL:-}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-}
    labels:
      createdBy: "Apps"
