services:
  this-week-in-past:
    image: "rouhim/this-week-in-past:2.3.5@sha256:bedb021d5ae74be97cb0c6781deb3d85c83a904a59a638f0bb15e1112ffaae27"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - RESOURCE_PATHS=/resources
      - DATA_FOLDER=/data
      - PORT=8080
      - SLIDESHOW_INTERVAL=${SLIDESHOW_INTERVAL}
      - RANDOM_SLIDESHOW=${RANDOM_SLIDESHOW}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${PHOTO_LIBRARY_PATH}:/resources:ro"
      - "${APP_DATA_DIR}:/data"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
