networks:
  1panel-network:
    external: true
services:
  yaak:
    image: "linuxserver/yaak:2026.8.1"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_HTTPS}:3001"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - CUSTOM_USER=${CUSTOM_USER}
      - PASSWORD=${PASSWORD}
      - TITLE=${TITLE:-Yaak}
      - SELKIES_UI_TITLE=${SELKIES_UI_TITLE:-Selkies}
      - DASHBOARD=${DASHBOARD:-selkies-dashboard}
      - LC_ALL=${LC_ALL}
    labels:
      createdBy: "Apps"
