services:
  immich-kiosk:
    image: "ghcr.io/damongolding/immich-kiosk:0.44.0@sha256:b8d3f19dba36bfe7004f231cf238eb4e1ac21ebae9f57800e455196ed4a5c899"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_BIND_ADDRESS}:${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - LANG=en_US
      - TZ=${TIME_ZONE}
      - KIOSK_PORT=3000
      - KIOSK_IMMICH_URL=${KIOSK_IMMICH_URL}
      - KIOSK_IMMICH_API_KEY=${KIOSK_IMMICH_API_KEY}
      - KIOSK_IMMICH_EXTERNAL_URL=${KIOSK_IMMICH_EXTERNAL_URL}
      - KIOSK_DURATION=${KIOSK_DURATION}
      - KIOSK_ALBUMS=${KIOSK_ALBUMS}
      - KIOSK_SHOW_TIME=${KIOSK_SHOW_TIME}
      - KIOSK_LAYOUT=${KIOSK_LAYOUT}
      - KIOSK_BEHIND_PROXY=true
    healthcheck:
      test: ["CMD", "/kiosk", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      createdBy: Apps

networks:
  1panel-network:
    external: true
