networks:
  1panel-network:
    external: true
services:
  healthchecks:
    image: "linuxserver/healthchecks:4.4.20261005"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
      - "${PANEL_APP_PORT_SMTP}:2525"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - SECRET_KEY=${SECRET_KEY}
      - SITE_ROOT=${SITE_ROOT}
      - SITE_NAME=${SITE_NAME}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - APPRISE_ENABLED=${APPRISE_ENABLED}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=${INTEGRATIONS_ALLOW_PRIVATE_IPS}
      - DEBUG=${HEALTHCHECKS_DEBUG}
      - PING_EMAIL_DOMAIN=${PING_EMAIL_DOMAIN}
      - RP_ID=${RP_ID}
      - SITE_LOGO_URL=${SITE_LOGO_URL}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-}
      - EMAIL_HOST=${EMAIL_HOST:-}
      - EMAIL_PORT=${EMAIL_PORT:-}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    labels:
      createdBy: "Apps"
