networks:
  1panel-network:
    external: true
services:
  emby:
    image: "linuxserver/emby:4.10.1"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8096"
      - "${PANEL_APP_PORT_HTTPS}:8920"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${TV_PATH}:/data/tvshows"
      - "${MOVIES_PATH}:/data/movies"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"
